# conda env create -f environment.yml
# conda activate metro-insight
name: metro-insight
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - -r requirements.txt
      - -e .
